using System;
using System.Numerics;
using Dalamud.Bindings.ImGui;

namespace XivHubPluginKit.UI;

/// <summary>
/// The theme's settings UI, generated by walking the same option table
/// <see cref="HubStyle.Push"/> walks. A plugin gets the whole editor by calling
/// <see cref="Draw"/> from a config window; adding a themed value to the table
/// grows a row here with no edit.
/// </summary>
public static class HubThemeEditor
{
    /// <summary>Draw the editor. Returns true if anything changed this frame.</summary>
    public static bool Draw(HubThemeConfigService config)
    {
        bool changed = false;

        bool enabled = config.Current.Enabled;
        if (ImGui.Checkbox("Use the XIV Hub theme", ref enabled))
        {
            config.Current.Enabled = enabled;
            config.Save();
            changed = true;
        }
        Help("Off leaves every window in your own Dalamud style.\n"
             + "The setting is shared, so it applies to every XIV Hub plugin at once.");

        if (!enabled)
            return changed;

        ImGui.Spacing();

        if (ImGui.CollapsingHeader($"Colours ({HubStyle.Colors.Count})###hubthemecolors"))
            changed |= DrawColors(config);

        if (ImGui.CollapsingHeader($"Geometry ({HubStyle.Floats.Count + HubStyle.Vectors.Count})###hubthemegeom"))
            changed |= DrawGeometry(config);

        ImGui.Spacing();
        ImGui.Separator();
        ImGui.Spacing();

        if (ImGui.Button("Reset all"))
        {
            config.ClearAll();
            changed = true;
        }
        ImGui.SameLine();
        ImGui.TextColored(HubStyle.Faint,
            $"{config.Current.StyleOverrides.Count + config.Current.Palette.Count} override(s) · {config.Path_}");

        return changed;
    }

    private static bool DrawColors(HubThemeConfigService config)
    {
        bool changed = false;
        using var _ = new Indent();

        foreach (var option in HubStyle.Colors)
        {
            var value = HubStyle.Resolve(option);
            if (ImGui.ColorEdit4($"{option.Label}###{option.Key}", ref value,
                    ImGuiColorEditFlags.AlphaBar | ImGuiColorEditFlags.AlphaPreviewHalf
                    | ImGuiColorEditFlags.NoInputs))
            {
                config.SetColor(option.Key, value);
                changed = true;
            }

            if (config.Current.StyleOverrides.ContainsKey(option.Key))
            {
                ImGui.SameLine();
                if (ImGui.SmallButton($"Reset###reset{option.Key}"))
                {
                    config.Clear(option.Key);
                    changed = true;
                }
            }

            ImGui.SameLine();
            ImGui.TextColored(HubStyle.Faint, option.ColorName);

            if (option.Description is { Length: > 0 })
                Help(option.Description);
        }

        return changed;
    }

    private static bool DrawGeometry(HubThemeConfigService config)
    {
        bool changed = false;
        using var _ = new Indent();

        foreach (var option in HubStyle.Vectors)
        {
            var value = HubStyle.Resolve(option);
            if (ImGui.DragFloat2($"{option.Label}###{option.Key}", ref value, 0.25f, 0f, 40f, "%.0f"))
            {
                config.SetVector2(option.Key, value);
                changed = true;
            }
            changed |= ResetButton(config, option.Key);
            if (option.Description is { Length: > 0 })
                Help(option.Description);
        }

        foreach (var option in HubStyle.Floats)
        {
            float value = HubStyle.Resolve(option);
            if (ImGui.DragFloat($"{option.Label}###{option.Key}", ref value, 0.1f,
                    option.Min, option.Max, "%.1f"))
            {
                config.SetFloat(option.Key, value);
                changed = true;
            }
            changed |= ResetButton(config, option.Key);
            if (option.Description is { Length: > 0 })
                Help(option.Description);
        }

        return changed;
    }

    private static bool ResetButton(HubThemeConfigService config, string key)
    {
        if (!config.Current.StyleOverrides.ContainsKey(key))
            return false;
        ImGui.SameLine();
        if (!ImGui.SmallButton($"Reset###reset{key}"))
            return false;
        config.Clear(key);
        return true;
    }

    private static void Help(string text)
    {
        ImGui.SameLine();
        ImGui.TextColored(HubStyle.Faint, "(?)");
        if (ImGui.IsItemHovered())
            ImGui.SetTooltip(text);
    }

    private readonly struct Indent : IDisposable
    {
        public Indent() => ImGui.Indent();
        public void Dispose() => ImGui.Unindent();
    }
}
